#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Ko Yamaguchi yamaguchiao1031@gmail.com
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans +=float(line)

print(ans)


